name: iot_project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  firebase_messaging: ^15.1.6
  mqtt_client: ^10.0.0
  flutter_local_notifications: ^12.0.0
  firebase_core: ^3.9.0


dev_dependencies:
  build_runner: ^2.4.6
  mockito: ^5.0.17
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true


